Wdp240601-14
odevpl/wdp-2406 pull request #18
Opened 2024-05-26 16:17 UTC by DanielTheEntomologist

Waliłem głową w ścianę i chciałem podciąć sobie żyły.
Zamiast tego założyłem kask i przebiłem ścianę.
Ale ktoś kto, będzie miał to po mnie modyfikować może też mieć mordercze myśli x-)

2024-05-28 13:33 UTC, Awerroes569 requested changes
z ticketa: "na mniejszych ekranach ma być wyszukiwanie i obok niego ikona mobilnego menu, które po rozwinięciu ma pokazywać dropdown przykrywający treść strony"
uwagi:
1. nie ma wdrożenia ikony mobilnego menu.

2024-05-29 22:44 UTC, DanielTheEntomologist commented
Poprawione - proszę o pulla

2024-06-01 17:03 UTC, Awerroes569 requested changes
funkcjonalnie wszystko działa;
zostawiłeś sporo kodu w komentarzach //
please zrob clean tego kodu i juz merguje

2024-06-01 18:16 UTC, DanielTheEntomologist commented
Ok.  To o godzinie 22 dopiero

On Sat, 1 Jun 2024, 19:03 Awerroes569, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> funkcjonalnie wszystko działa;
> zostawiłeś sporo kodu w komentarzach //
> please zrob clean tego kodu i juz merguje
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/odevpl/wdp-2406/pull/18#pullrequestreview-2092142195>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5A7EE4FUZF7IUPUMNSEQ4TZFH5F5AVCNFSM6AAAAABIJ5L3JKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOJSGE2DEMJZGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-01 21:07 UTC, DanielTheEntomologist commented
poprawione

2024-06-02 06:42 UTC, Awerroes569 approved these changes
ok

2024-06-02 06:42 UTC, merged