Wdp240601 3
odevpl/wdp-2406 pull request #7
Opened 2024-05-18 15:56 UTC by Awerroes569

PROBLEM:
every FeatureBox component should be link and react on hover state by adding 'active' class
SOLUTION:
- adding 'target' prop to FeatureBox to establish link (not required);
- implementing useState to manage hover state for FeatureBox component;
- adding function to redirect to target when FeatureBox is clicked (using scrollIntoView).
TESTS:
adding 3 tests:
- 'should not call scrollIntoView when clicked without a target';
- 'should call scrollIntoView when target element is found';
- 'should add active class when hovered over and remove it when mouse leaves'.

WARNING:
to enable tests some modifications to package.json and yarn.lock were added;
commit "cleaning code" includes all changes without changes to files mentioned above.

2024-05-24 20:36 UTC, Awerroes569 commented
cofnąłem się do commit "cleaning code": obecnie nie ma zmian yarn.lock i package.json oraz nie ma testow

2024-05-24 20:56 UTC, tkrzywosadzki requested changes
Przetestowane manualnie, hover dziala. W tickecie jest wzmianka o tym zeby zrobic tez z tego linki, takze trzeba jeszcze opakowac kazdy ten element w features/FeatureBoxes/FeatureBoxes.js w link

2024-05-24 21:15 UTC, Awerroes569 commented
> Przetestowane manualnie, hover dziala. W tickecie jest wzmianka o tym zeby zrobic tez z tego linki, takze trzeba jeszcze opakowac kazdy ten element w features/FeatureBoxes/FeatureBoxes.js w link

próbowałem przerobić to na początku jako <a> ale kompletnie rozsypywały się style;
finalnie cały komponent po click zachowuje się jak link;
ponadto dostaje w props "target", który jest tożsamy z linkiem;
żeby to sprawdzić możesz zrobić element z jakimś id a potem podstawic target=id w ktoryms z FeatureBox

2024-05-26 21:25 UTC, Awerroes569 commented
usunąłem zbędne testy;
usunąłem zbędne funkcjonalności;
obudowałem komponenty FeatureBox wrapperem <a>

2024-05-26 22:16 UTC, tkrzywosadzki approved these changes
teraz smiga :)

2024-05-26 22:16 UTC, merged